name: fluttrap
description: "Fluttrap is a Bootstrap inspired UI framework for Flutter that helps developers build responsive, scalable apps faster using prebuilt widgets, layouts, and theme utilities."
version: 0.0.1
homepage: https://fluttrap.belovance.com
repository: https://github.com/belovance/fluttrap
issue_tracker: https://github.com/belovance/fluttrap/issues
documentation: https://fluttrap.belovance.com
topics: [ui, widgets, layouts, utilities, bootstrap]
funding:
  [https://github.com/sponsors/belovance, https://buymeacoffee.com/belovance]

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

screenshots:
  - description: The Fluttrap Logo
    path: screenshots/fluttrap-logo.png
